### PR TITLE
Changed to README, adding geo method for future casing.

### PR DESCRIPTION
**Pull request by aguynamedjoetoo**

### CODE REVIEW

**Comment by aguynamedjoetoo** [comment]
It sure does. Trust me, I'm an engineer.

**Comment by ellisandy** [comment]
Oh good. Then your rspec won't be hard. ;) 

Let me know if you need some help crafting the rspec

**Comment by aguynamedjoetoo** [comment]
fml you rubyists

**Comment by aguynamedjoetoo** [comment]
Updated, just for you. rspec only fails because of VCR complaining about not being able to function with the URL for google via geocoder, values are just fine and rspec is just fine

**Pull request merged**
